name: Build and Deploy Gradle Project

on:
  push:
    branches: [ "ver2" ]
  pull_request:
    branches: [ "ver2" ]

jobs:
  build:
    name: Build Gradle Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.3'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}
    
    - name: Build with Gradle Wrapper
      run: ./gradlew clean bootJar

    - name: Verify JAR File
      run: ls -l build/libs/

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: insurance-service
        path: build/libs/insurance-service-0.0.1-SNAPSHOT.jar

  deploy-ec2-1:
    name: Deploy to EC2 Instance 1
    runs-on: ubuntu-latest
    needs: build
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: insurance-service

    - name: Deploy to EC2 Instance 1
      run: |
        echo "$PRIVATE_KEY" > /tmp/aws-insurance-service-1.pem
        chmod 600 /tmp/aws-insurance-service-1.pem
        scp -v -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no insurance-service-0.0.1-SNAPSHOT.jar ubuntu@3.36.41.107:/home/ubuntu/
        ssh -v -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no ubuntu@3.36.41.107 << 'EOF'
        pkill -f 'insurance-service-0.0.1-SNAPSHOT.jar' || true
        nohup java -jar /home/ubuntu/insurance-service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
        EOF

  deploy-ec2-2:
    name: Deploy to EC2 Instance 2
    runs-on: ubuntu-latest
    needs: build
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: insurance-service

    - name: Deploy to EC2 Instance 2
      run: |
        echo "$PRIVATE_KEY" > /tmp/aws-insurance-service-2.pem
        chmod 600 /tmp/aws-insurance-service-2.pem
        scp -v -i /tmp/aws-insurance-service-2.pem -o StrictHostKeyChecking=no insurance-service-0.0.1-SNAPSHOT.jar ubuntu@3.34.73.7:/home/ubuntu/
        ssh -v -i /tmp/aws-insurance-service-2.pem -o StrictHostKeyChecking=no ubuntu@3.34.73.7 << 'EOF'
        pkill -f 'insurance-service-0.0.1-SNAPSHOT.jar' || true
        nohup java -jar /home/ubuntu/insurance-service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
        EOF
