name: Build and Deploy Gradle Project

on:
  push:
    branches: [ "ver2" ]
  pull_request:
    branches: [ "ver2" ]

jobs:
  build-and-deploy:
    name: Build and Deploy Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.3'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}
    
    - name: Build with Gradle Wrapper
      run: ./gradlew clean bootJar

    - name: Verify JAR File
      run: ls -l build/libs/

    - name: Compress JAR File
      run: zip insurance-service.zip build/libs/insurance-service-0.0.1-SNAPSHOT.jar

    - name: Deploy to EC2
      run: |
        # Save private key for SSH access
        echo "$PRIVATE_KEY" > /tmp/aws-insurance-service-1.pem
        chmod 600 /tmp/aws-insurance-service-1.pem
        # Deploy to EC2 Instance 1
        scp -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no insurance-service.zip ubuntu@3.36.41.107:/home/ubuntu/
        ssh -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no ubuntu@3.36.41.107 << 'EOF'
        unzip -o /home/ubuntu/insurance-service.zip -d /home/ubuntu/
        pkill -f 'insurance-service-0.0.1-SNAPSHOT.jar' || true
        nohup java -jar /home/ubuntu/insurance-service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
        EOF
        # Deploy to EC2 Instance 2
        scp -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no insurance-service.zip ubuntu@3.34.73.7:/home/ubuntu/
        ssh -i /tmp/aws-insurance-service-1.pem -o StrictHostKeyChecking=no ubuntu@3.34.73.7 << 'EOF'
        unzip -o /home/ubuntu/insurance-service.zip -d /home/ubuntu/
        pkill -f 'insurance-service-0.0.1-SNAPSHOT.jar' || true
        nohup java -jar /home/ubuntu/insurance-service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
        EOF
