name: Build and Deploy Gradle Project
on:
  push:
    branches: [ "ver2" ]
  pull_request:
    branches: [ "ver2" ]

jobs:
  build-and-deploy:
    name: Build and Deploy to AWS EC2
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.3'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i <(echo "$PRIVATE_KEY") build/libs/insurance-service-0.0.1-SNAPSHOT.jar ec2-user@13.125.148.26:/home/ec2-user/
        ssh -o StrictHostKeyChecking=no -i <(echo "$PRIVATE_KEY") ec2-user@13.125.148.26 << 'EOF'
        pkill -f 'insurance-service-0.0.1-SNAPSHOT.jar' || true
        nohup java -jar /home/ec2-user/insurance-service-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
        EOF
